const adventPrizes = [
  {
    id: 1,
    name: "Cats in Hats Calendar",
    description: "Every month features a new grumpy cat wearing an increasingly ridiculous hat.",
    url: "www.google.com",
    json: "",
    image: "",
  },
  {
    id: 2,
    name: 'The "What Day is It?" Calendar',
    description: 'Every date is labeled as "Today." Hope you like guessing deadlines.',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 3,
    name: "12 Months of Sexy Vegetables",
    description: "Steamy photos of seductive carrots, sultry zucchinis, and provocative potatoes.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 4,
    name: "The Eternal Mondays Calendar",
    description: "Every day is Monday. A nightmare in calendar form.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 5,
    name: "Doomsday Prepper’s Calendar",
    description: "Track apocalyptic events alongside tips for canning beans and making bunker beds.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 6,
    name: "Dogs in Business Suits Calendar",
    description: 'Good boys dressed for success. Includes puns like "Barketing Manager" and "CEO Pup."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 7,
    name: "The Passive-Aggressive Reminder Calendar",
    description: 'Daily notes like "Clean your damn house" and "You forgot Mom’s birthday again."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 8,
    name: "Bathroom Thoughts Calendar",
    description: 'Features profound (and stupid) thoughts like "Do fish get thirsty?" or "Why is there a ‘D’ in fridge but not in refrigerator?"',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 9,
    name: "The NSFW Dad Joke Calendar",
    description: "A new, hilariously inappropriate dad joke every day. Not suitable for work or kids.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 10,
    name: "12 Months of Angry Geese",
    description: "Photos of furious geese looking like they’re plotting your demise.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 11,
    name: "The Hangover Planner",
    description: "Mark your days with how hungover you’ll be. January 1 is a write-off.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 12,
    name: "The Cursing Calendar",
    description: "A new swear word or insult for every day. Expand your vocabulary!",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 13,
    name: "Holiday Movie Quote Calendar",
    description: 'Daily quotes from your favorite holiday films. December 24: "Yippee Ki-Yay!"',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 14,
    name: "The Procrastinator’s Planner",
    description: 'Every day says "Do it tomorrow." A perfect gift for your laziest friend.',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 15,
    name: "2024 Meme Calendar",
    description: "Keep track of the year with daily memes. Warning: already outdated by February.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 16,
    name: "Pigeon of the Month Club",
    description: "A calendar dedicated to the most majestic (and terrifying) city birds.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 17,
    name: "The Spite Calendar",
    description: "Tracks birthdays, deadlines, and reminders for people you want to ignore.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 18,
    name: "Awkward Family Photos Calendar",
    description: "12 months of cringy family portraits. Bonus: includes mullets.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 19,
    name: "The Useless Holiday Calendar",
    description: 'Marks all the ridiculous holidays like "National Taco Appreciation Day" or "Talk Like a Pirate Day."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 20,
    name: "The Wine Drinker’s Calendar",
    description: 'A guide to pair each day of the year with wine. January 1: "Just drink straight from the bottle."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 21,
    name: "The Ex-Tracker",
    description: "Reminds you of all your exes’ birthdays so you know when to avoid social media.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 22,
    name: "The Paranoid Planner",
    description: 'Daily advice like "Don’t trust anyone today" or "Wear tinfoil."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 23,
    name: "Llamas in Pajamas Calendar",
    description: "Each month features adorable llamas dressed for bedtime.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 24,
    name: "How Not to Adult Calendar",
    description: 'Daily tips on avoiding responsibility. Day 1: "Buy Legos instead of groceries."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 25,
    name: "Calendar of Regrettable Tattoos",
    description: '12 months of the worst tattoos ever inked. Day 1: A misspelled "No Regerts."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 26,
    name: "Office Fridge Violation Tracker",
    description: "Daily logs of the horrifying things found in the company fridge.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 27,
    name: "The Conspiracy Moon Calendar",
    description: 'Every month has "proof" the moon landing was fake, except July: "Eh, maybe."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 28,
    name: "The Bigfoot Sighting Calendar",
    description: 'Track the most "legit" Bigfoot sightings of the year. Hint: they’re all blurry.',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 29,
    name: "12 Months of Bad Parking",
    description: "Photos of the world’s most inconsiderate park jobs. Day 3: A car across 4 spaces.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 30,
    name: 'The "I’ll Be Better Tomorrow" Calendar',
    description: 'A year of unkept promises. January 1: "Join a gym!" December 31: "Next year."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 31,
    name: "Calendars for Goldfish",
    description: 'Every day is labeled "Feed me." It resets every 3 seconds.',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 32,
    name: "The Candle Sniffer’s Calendar",
    description: 'A new scent idea every day. Day 7: "Burnt toast and regret."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 33,
    name: "12 Months of Dads Grilling",
    description: "Photos of dads standing proudly next to grills. No food, just the grill.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 34,
    name: "Birds Flipping the Bird",
    description: "Daily photos of birds that look like they’re flipping you off.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 35,
    name: "The Overworked Plant Calendar",
    description: "Daily reminders to water your damn plants. Spoiler: You still forget.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 36,
    name: "The Overpriced Coffee Calendar",
    description: "Each day features a $10 coffee you’ll regret ordering. Day 24: Unicorn Latte.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 37,
    name: "12 Months of Failed Pinterest Projects",
    description: 'Photos of crafts gone horribly wrong. Day 1: "Cake that looks like a crime scene."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 38,
    name: 'The "Who Farted?" Calendar',
    description: 'A year of side-eye-worthy moments. January: "Definitely Greg."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 39,
    name: "The Haters Gonna Hate Calendar",
    description: "Motivational quotes paired with people giving you dirty looks.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 40,
    name: "The Overcomplicated Excel Calendar",
    description: "Tracks your life with pivot tables, VLOOKUPs, and a sense of dread.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 41,
    name: 'The "Why Is This Sticky?" Calendar',
    description: "Daily photos of mystery sticky substances. Answers not included.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 42,
    name: 'The "Oops, All Holidays" Calendar',
    description: 'Every day is a holiday. January 2: "National Overachievers’ Day."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 43,
    name: "Dogs Who Look Like Celebrities",
    description: "Each month features a dog that looks suspiciously like a famous person.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 44,
    name: 'The "I’ll Start Monday" Calendar',
    description: "A year of excuses for not doing the thing. Spoiler: You never start.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 45,
    name: "12 Months of Tiny Violins",
    description: "Photos of people needing a tiny violin for their ridiculous complaints.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 46,
    name: "The Cat Butt Calendar",
    description: "12 months of cats showing you their rear ends. February: Fluffy’s revenge.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 47,
    name: "The Middle Finger Calendar",
    description: "Each day features a new creative way to flip someone off. December 25: Holiday edition.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 48,
    name: 'The "What Could Go Wrong?" Calendar',
    description: "Photos of moments right before something went hilariously wrong.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 49,
    name: "The Office Excuse Generator",
    description: 'Daily excuses to avoid work. Day 1: "I have a dentist appointment for my goldfish."',
    url: "",
    json: "",
    image: "",
  },
  {
    id: 50,
    name: "The Everything Bagel Calendar",
    description: "Each day reveals a bagel with increasingly weird toppings. December 24: Tuna and sprinkles.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 51,
    name: 'The "I’m Not Crying, You Are" Calendar',
    description: "Daily tear-jerking quotes and photos. February 14: A puppy meeting its new owner.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 52,
    name: "12 Months of Failed Jump Shots",
    description: "Photos of people trying to jump for the camera. Day 3: Grandma’s knees gave out.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 53,
    name: "The Lazy Gamer Calendar",
    description: "Daily excuses for skipping chores to play video games.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 54,
    name: "The Spilled Coffee Calendar",
    description: "A new stain pattern every day. January 8: Looks like the Mona Lisa.",
    url: "",
    json: "",
    image: "",
  },
  {
    id: 55,
    name: 'The "I Need a Vacation" Calendar',
    description: "Daily tropical photos paired with a reminder that you’re still broke.",
    url: "",
    json: "",
    image: "",
  },
];

export default adventPrizes;
